/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customize_preferences;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Class that will open a window for adding client preferences.
 * @author Robert
 */
public class AddClientGUI extends javax.swing.JFrame {
    
    /**
     * Creates new AddClientGUI object and initialize its components.
     */
    public AddClientGUI() {
        getContentPane().setBackground( new Color(200, 100, 100));
        initComponents();
    }

    /**
     * Checks that the text fields from the interface are set.
     * @return false if one of the text field is not set, true otherwise.
     */
        public boolean isTextFieldsValuesSet(){
        
        if( criteriu1TextField.getText().isEmpty() ||
            criteriu2TextField.getText().isEmpty() ||
            criteriu3TextField.getText().isEmpty() ||
            criteriu4TextField.getText().isEmpty() ||
            criteriu5TextField.getText().isEmpty() ||
            criteriu6TextField.getText().isEmpty() ||
            criteriu7TextField.getText().isEmpty() ||
            criteriu8TextField.getText().isEmpty()
                ){
            return false;
        }else{
             return true;
        }
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        insertClientButton = new javax.swing.JButton();
        criteriu1Label = new javax.swing.JLabel();
        criteriu2Label = new javax.swing.JLabel();
        criteriu3Label = new javax.swing.JLabel();
        criteriu4Label = new javax.swing.JLabel();
        criteriu5Label = new javax.swing.JLabel();
        criteriu6Label = new javax.swing.JLabel();
        criteriu7Label = new javax.swing.JLabel();
        criteriu8Label = new javax.swing.JLabel();
        criteriu1TextField = new javax.swing.JFormattedTextField();
        criteriu2TextField = new javax.swing.JFormattedTextField();
        criteriu3TextField = new javax.swing.JFormattedTextField();
        criteriu4TextField = new javax.swing.JFormattedTextField();
        criteriu5TextField = new javax.swing.JFormattedTextField();
        criteriu6TextField = new javax.swing.JFormattedTextField();
        criteriu7TextField = new javax.swing.JFormattedTextField();
        criteriu8TextField = new javax.swing.JFormattedTextField();

        jFormattedTextField2.setText("jFormattedTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personalizare preferinte client");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        insertClientButton.setBackground(new java.awt.Color(102, 102, 102));
        insertClientButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        insertClientButton.setText("<html>\n<p align=\"center\">Trimite preferinte catre agentul Furnizor </p>\n</html>");
        insertClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertClientButtonActionPerformed(evt);
            }
        });

        criteriu1Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu1Label.setText("Criteriu 1");

        criteriu2Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu2Label.setText("Criteriu 2");

        criteriu3Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu3Label.setText("Criteriu 3");

        criteriu4Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu4Label.setText("Criteriu 4");

        criteriu5Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu5Label.setText("Criteriu 5");

        criteriu6Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu6Label.setText("Criteriu 6");

        criteriu7Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu7Label.setText("Criteriu 7");

        criteriu8Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu8Label.setText("Criteriu 8");

        criteriu1TextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        criteriu1TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                criteriu1TextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criteriu1Label)
                            .addComponent(criteriu2Label)
                            .addComponent(criteriu3Label)
                            .addComponent(criteriu4Label)
                            .addComponent(criteriu5Label)
                            .addComponent(criteriu7Label)
                            .addComponent(criteriu8Label)
                            .addComponent(criteriu6Label))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(criteriu2TextField)
                            .addComponent(criteriu1TextField)
                            .addComponent(criteriu3TextField)
                            .addComponent(criteriu4TextField)
                            .addComponent(criteriu5TextField)
                            .addComponent(criteriu6TextField)
                            .addComponent(criteriu7TextField)
                            .addComponent(criteriu8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(insertClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu1Label)
                    .addComponent(criteriu1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(criteriu2Label)
                    .addComponent(criteriu2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(criteriu3Label)
                    .addComponent(criteriu3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu4Label)
                    .addComponent(criteriu4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu5Label)
                    .addComponent(criteriu5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu6Label)
                    .addComponent(criteriu6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu7Label)
                    .addComponent(criteriu7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu8Label)
                    .addComponent(criteriu8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(insertClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertClientButtonActionPerformed
        insertClientButtonClicked();
    }//GEN-LAST:event_insertClientButtonActionPerformed
    
    /**
     * Insert a client preference in clienti table.
     */
    private void insertClientButtonClicked(){
        if (isTextFieldsValuesSet()) {
            Client client = new Client();
            client.setCriteriu1(Integer.valueOf(criteriu1TextField.getText()));
            client.setCriteriu2(Integer.valueOf(criteriu2TextField.getText()));
            client.setCriteriu3(Integer.valueOf(criteriu3TextField.getText()));
            client.setCriteriu4(Integer.valueOf(criteriu4TextField.getText()));
            client.setCriteriu5(Integer.valueOf(criteriu1TextField.getText()));
            client.setCriteriu6(Integer.valueOf(criteriu1TextField.getText()));
            client.setCriteriu7(Integer.valueOf(criteriu1TextField.getText()));
            client.setCriteriu8(Integer.valueOf(criteriu1TextField.getText()));
            DatabaseManager.instance.insertClient(client);
            new JOptionPane().showMessageDialog(this, "Client inserat");
        }
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        FrameInstanceHolder.instance.setAddClientFrame( null );
    }//GEN-LAST:event_formWindowClosed

    private void criteriu1TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_criteriu1TextFieldFocusLost
        // TODO add your handling code here:
        System.out.println("Focus lost");
    }//GEN-LAST:event_criteriu1TextFieldFocusLost



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel criteriu1Label;
    private javax.swing.JFormattedTextField criteriu1TextField;
    private javax.swing.JLabel criteriu2Label;
    private javax.swing.JFormattedTextField criteriu2TextField;
    private javax.swing.JLabel criteriu3Label;
    private javax.swing.JFormattedTextField criteriu3TextField;
    private javax.swing.JLabel criteriu4Label;
    private javax.swing.JFormattedTextField criteriu4TextField;
    private javax.swing.JLabel criteriu5Label;
    private javax.swing.JFormattedTextField criteriu5TextField;
    private javax.swing.JLabel criteriu6Label;
    private javax.swing.JFormattedTextField criteriu6TextField;
    private javax.swing.JLabel criteriu7Label;
    private javax.swing.JFormattedTextField criteriu7TextField;
    private javax.swing.JLabel criteriu8Label;
    private javax.swing.JFormattedTextField criteriu8TextField;
    private javax.swing.JButton insertClientButton;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    // End of variables declaration//GEN-END:variables
}
