/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customize_preferences;

import java.awt.Color;
import java.sql.SQLException;


/**
 * The JFrame class CustomizePreferences is the main class 
 * of this project!
 * @author Robert
 */
public class CustomizePreferences extends javax.swing.JFrame {
    
    /**
     * <p>
     * Creates a new instance of CustomizePreferences JFrame. <br>
     * When this class is instantiated the following actions are made:<br>
     * 1. a connection with the database is managed <br>
     * 2. the components of the JFrame are also instantiated <br>
     * 3. the window is centered on screen
     */
    public CustomizePreferences() {
        getContentPane().setBackground( new Color(200, 100, 100) );
        //getContentPane().setBackground( new Color( 0,204,255 ) );
        initComponents();
        this.setLocationRelativeTo( null );
        DatabaseManager.instance.connect();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitleLabel = new javax.swing.JLabel();
        clientButton = new javax.swing.JButton();
        providerButton = new javax.swing.JButton();
        resetDataButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interfata principala");
        setBackground(new java.awt.Color(0, 204, 255));
        setResizable(false);

        mainTitleLabel.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        mainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleLabel.setText("Sistem informatic pentru personalizarea preferintelor clientilor si generarea de oferte");

        clientButton.setBackground(new java.awt.Color(102, 102, 102));
        clientButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        clientButton.setText("<html> \n<p align=\"center\">Deschide interfata pentru clienti </p>\n</html>");
        clientButton.setToolTipText("");
        clientButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clientButton.setMinimumSize(new java.awt.Dimension(145, 23));
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });

        providerButton.setBackground(new java.awt.Color(102, 102, 102));
        providerButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        providerButton.setText("<html>  <p align=\"center\">Deschide interfata pentru furnizorul de produse/servicii </p> </html>");
        providerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        providerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerButtonActionPerformed(evt);
            }
        });

        resetDataButton.setBackground(new java.awt.Color(102, 102, 102));
        resetDataButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        resetDataButton.setText("Reset Data");
        resetDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(clientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(providerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addComponent(mainTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetDataButton)
                .addGap(419, 419, 419))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(providerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(resetDataButton)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        clientButtonClicked();
    }//GEN-LAST:event_clientButtonActionPerformed

    /**
     * <p>
     * Opens the Clienti window.
     */
    private void clientButtonClicked(){
        if( FrameInstanceHolder.instance.getClientsFrame() == null ){
            ClientsGUI clientsFrame = new ClientsGUI();
            FrameInstanceHolder.instance.setClientsFrame( clientsFrame );
            clientsFrame.setVisible( true );
        }else{
            FrameInstanceHolder.instance.getClientsFrame().toFront();
        }
    }
    
    private void providerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerButtonActionPerformed
        // TODO add your handling code here:
        providerButtonClicked();
    }//GEN-LAST:event_providerButtonActionPerformed
    
    /**
     * <p>
     * Opens the Agent Furnizor window.
     */
    private void providerButtonClicked(){
        if( FrameInstanceHolder.instance.getProviderFrame()== null ){
            ProviderGUI providerFrame = new ProviderGUI();
            FrameInstanceHolder.instance.setProviderFrame(providerFrame);
            providerFrame.setVisible( true );
        }else{
            FrameInstanceHolder.instance.getProviderFrame().toFront();
        }
    }
    
    /**
     * <p>
     * Reseting all data from DB.
     */
    private void resetDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDataButtonActionPerformed
        // TODO add your handling code here:
        if( DatabaseManager.instance.isConnected() ){
            try{
                DatabaseManager.instance.statement.executeUpdate( "DELETE FROM oferte" );
                DatabaseManager.instance.statement.executeUpdate( "DELETE FROM clienti" );
                DatabaseManager.instance.statement.executeUpdate( "DELETE FROM centroizi" );
                DatabaseManager.instance.statement.executeUpdate( "ALTER TABLE clienti AUTO_INCREMENT = 1" );
                DatabaseManager.instance.statement.executeUpdate( "ALTER TABLE oferte AUTO_INCREMENT = 1" );
                DatabaseManager.instance.statement.executeUpdate( "ALTER TABLE centroizi AUTO_INCREMENT = 1" );
                
            }catch( SQLException e){
                System.out.println(e.getMessage() );
            }
        }
    }//GEN-LAST:event_resetDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomizePreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomizePreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomizePreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomizePreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomizePreferences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientButton;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JButton providerButton;
    private javax.swing.JButton resetDataButton;
    // End of variables declaration//GEN-END:variables
}
