/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customize_preferences;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Class that will open a window for adding client preferences.
 * @author Robert
 */
public class AddClientGUI extends javax.swing.JFrame {
    
    /**
     * Creates new AddClientGUI object and initialize its components.
     */
    public AddClientGUI() {
        getContentPane().setBackground( new Color(200, 100, 100));
        initComponents();
        setComboBoxValues();
    }

    /**
     * Checks that the text fields from the interface are set.
     * @return false if one of the text field is not set, true otherwise.
     */
    public boolean areTextFieldsValuesSet() {
        if ( criteriu4TextField.getText().isEmpty()
                || criteriu5TextField.getText().isEmpty()
                || criteriu6TextField.getText().isEmpty()
                || criteriu7TextField.getText().isEmpty()
                || criteriu8TextField.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        insertClientButton = new javax.swing.JButton();
        criteriu1Label = new javax.swing.JLabel();
        criteriu2Label = new javax.swing.JLabel();
        criteriu3Label = new javax.swing.JLabel();
        criteriu4Label = new javax.swing.JLabel();
        criteriu5Label = new javax.swing.JLabel();
        criteriu6Label = new javax.swing.JLabel();
        criteriu7Label = new javax.swing.JLabel();
        criteriu8Label = new javax.swing.JLabel();
        criteriu4TextField = new javax.swing.JFormattedTextField();
        criteriu5TextField = new javax.swing.JFormattedTextField();
        criteriu6TextField = new javax.swing.JFormattedTextField();
        criteriu7TextField = new javax.swing.JFormattedTextField();
        criteriu8TextField = new javax.swing.JFormattedTextField();
        criteriu1ComboBox = new javax.swing.JComboBox();
        criteriu2ComboBox = new javax.swing.JComboBox();
        criteriu3ComboBox = new javax.swing.JComboBox();

        jFormattedTextField2.setText("jFormattedTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personalizare preferinte client");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        insertClientButton.setBackground(new java.awt.Color(102, 102, 102));
        insertClientButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        insertClientButton.setText("<html>\n<p align=\"center\">Trimite preferinte catre agentul Furnizor </p>\n</html>");
        insertClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertClientButtonActionPerformed(evt);
            }
        });

        criteriu1Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu1Label.setText("Criteriu 1");

        criteriu2Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu2Label.setText("Criteriu 2");

        criteriu3Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu3Label.setText("Criteriu 3");

        criteriu4Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu4Label.setText("Criteriu 4");

        criteriu5Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu5Label.setText("Criteriu 5");

        criteriu6Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu6Label.setText("Criteriu 6");

        criteriu7Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu7Label.setText("Criteriu 7");

        criteriu8Label.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        criteriu8Label.setText("Criteriu 8");

        criteriu1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        criteriu2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        criteriu3ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criteriu1Label)
                            .addComponent(criteriu2Label)
                            .addComponent(criteriu3Label)
                            .addComponent(criteriu4Label)
                            .addComponent(criteriu5Label)
                            .addComponent(criteriu7Label)
                            .addComponent(criteriu8Label)
                            .addComponent(criteriu6Label))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(criteriu4TextField)
                            .addComponent(criteriu5TextField)
                            .addComponent(criteriu6TextField)
                            .addComponent(criteriu7TextField)
                            .addComponent(criteriu8TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(criteriu1ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(criteriu2ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(criteriu3ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(insertClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu1Label)
                    .addComponent(criteriu1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu2Label)
                    .addComponent(criteriu2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu3Label)
                    .addComponent(criteriu3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu4Label)
                    .addComponent(criteriu4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu5Label)
                    .addComponent(criteriu5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu6Label)
                    .addComponent(criteriu6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu7Label)
                    .addComponent(criteriu7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriu8Label)
                    .addComponent(criteriu8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(insertClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertClientButtonActionPerformed
        insertClientButtonClicked();
    }//GEN-LAST:event_insertClientButtonActionPerformed
    
    /**
     * Insert a client preference in clienti table.
     */
    private void insertClientButtonClicked(){
        if (areTextFieldsValuesSet()) {
            Client client = new Client();
            client.setCriteriu1( (String) criteriu1ComboBox.getSelectedItem() );
            client.setCriteriu2( (String) criteriu2ComboBox.getSelectedItem() );
            client.setCriteriu3( (String) criteriu3ComboBox.getSelectedItem() );
            client.setCriteriu4(Integer.valueOf(criteriu4TextField.getText()));
            client.setCriteriu5(Integer.valueOf(criteriu5TextField.getText()));
            client.setCriteriu6(Integer.valueOf(criteriu6TextField.getText()));
            client.setCriteriu7(Integer.valueOf(criteriu7TextField.getText()));
            client.setCriteriu8(Integer.valueOf(criteriu8TextField.getText()));
            DatabaseManager.instance.insertClient(client);
            new JOptionPane().showMessageDialog(this, "Client inserat");
        }
    }
    
    private void setComboBoxValues(){
        DefaultComboBoxModel criteriu1Model = (DefaultComboBoxModel) criteriu1ComboBox.getModel();
        DefaultComboBoxModel criteriu2Model = (DefaultComboBoxModel) criteriu2ComboBox.getModel();
        DefaultComboBoxModel criteriu3Model = (DefaultComboBoxModel) criteriu3ComboBox.getModel();
        criteriu1Model.removeAllElements();
        criteriu2Model.removeAllElements();
        criteriu3Model.removeAllElements();
        
        criteriu1Model.addElement( "Mic" );
        criteriu1Model.addElement( "Mediu" );
        criteriu1Model.addElement( "Mare" );
        
        criteriu2Model.addElement( "iOS" );
        criteriu2Model.addElement( "Android" );
        criteriu2Model.addElement( "Windows Phone" );
        criteriu2Model.addElement( "BlackBerry OS" );
        
        criteriu3Model.addElement("Amoled");
        criteriu3Model.addElement("LED");
        criteriu3Model.addElement("IPS");
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        FrameInstanceHolder.instance.setAddClientFrame( null );
    }//GEN-LAST:event_formWindowClosed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox criteriu1ComboBox;
    private javax.swing.JLabel criteriu1Label;
    private javax.swing.JComboBox criteriu2ComboBox;
    private javax.swing.JLabel criteriu2Label;
    private javax.swing.JComboBox criteriu3ComboBox;
    private javax.swing.JLabel criteriu3Label;
    private javax.swing.JLabel criteriu4Label;
    private javax.swing.JFormattedTextField criteriu4TextField;
    private javax.swing.JLabel criteriu5Label;
    private javax.swing.JFormattedTextField criteriu5TextField;
    private javax.swing.JLabel criteriu6Label;
    private javax.swing.JFormattedTextField criteriu6TextField;
    private javax.swing.JLabel criteriu7Label;
    private javax.swing.JFormattedTextField criteriu7TextField;
    private javax.swing.JLabel criteriu8Label;
    private javax.swing.JFormattedTextField criteriu8TextField;
    private javax.swing.JButton insertClientButton;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    // End of variables declaration//GEN-END:variables
}
