/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proiectfinalinfoacademy;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.URLDataSource;
import javax.swing.*;

/**
 *
 * @author Robert
 */
public class GUI extends javax.swing.JFrame {
    protected CarteDeTelefon model;
    protected Connection c;
    protected Statement s;
    protected ResultSet rs;
    protected List<Abonat> l;
    private Random rand = new Random();
    private int randCurent;
    private ImageIcon i1;
    private ImageIcon i2;
    private ImageIcon i3;
    private int d;
    protected final String PASS = "infoacademy";
    protected GUIPass gPass;
    /**
     * Creates new form GUI
     */
    
    public GUI() {
            initComponents();
            closeDB();
            refreshDB();
            banner();
            setMnemonics();
            
            
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFileChooser1 = new javax.swing.JFileChooser();
        bgCautare = new javax.swing.ButtonGroup();
        bgNumarTelefon = new javax.swing.ButtonGroup();
        bgOrdonare = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bAdauga = new javax.swing.JButton();
        bSterge = new javax.swing.JButton();
        bModifica = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lNume = new javax.swing.JLabel();
        lPrenume = new javax.swing.JLabel();
        lCnp = new javax.swing.JLabel();
        lNrTel = new javax.swing.JLabel();
        tfNume = new javax.swing.JTextField();
        tfPrenume = new javax.swing.JTextField();
        tfCnp = new javax.swing.JTextField();
        tfNrTelefon = new javax.swing.JTextField();
        rbNrMobil = new javax.swing.JRadioButton();
        rbNrFix = new javax.swing.JRadioButton();
        bRefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jrbOrdoneazaNume = new javax.swing.JRadioButton();
        jrbOrdoneazaPrenume = new javax.swing.JRadioButton();
        jrbOrdoneazaCnp = new javax.swing.JRadioButton();
        jrbOrdoneazaNumar = new javax.swing.JRadioButton();
        jpReclame = new javax.swing.JPanel();
        jlPoza = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jOpen = new javax.swing.JMenuItem();
        jSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jExit = new javax.swing.JMenuItem();
        jmAdauga = new javax.swing.JMenu();
        jAdauga = new javax.swing.JMenuItem();
        jSterge = new javax.swing.JMenuItem();
        jModifica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmHelp = new javax.swing.JMenu();
        jConnect = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(30000, 30000));
        setMinimumSize(new java.awt.Dimension(900, 950));
        setPreferredSize(new java.awt.Dimension(900, 950));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        bAdauga.setText("Adauga");
        bAdauga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAdauga.setMaximumSize(new java.awt.Dimension(71, 23));
        bAdauga.setMinimumSize(new java.awt.Dimension(71, 23));
        bAdauga.setPreferredSize(new java.awt.Dimension(71, 23));
        bAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugaActionPerformed(evt);
            }
        });

        bSterge.setText("Sterge");
        bSterge.setMaximumSize(new java.awt.Dimension(71, 23));
        bSterge.setMinimumSize(new java.awt.Dimension(71, 23));
        bSterge.setPreferredSize(new java.awt.Dimension(71, 23));
        bSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStergeActionPerformed(evt);
            }
        });

        bModifica.setText("Modifica");
        bModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificaActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        lNume.setText("Nume:");

        lPrenume.setText("Prenume:");

        lCnp.setText("Cnp:");

        lNrTel.setText("Numar telefon:");

        bgNumarTelefon.add(rbNrMobil);
        rbNrMobil.setText("Numar mobil");

        bgNumarTelefon.add(rbNrFix);
        rbNrFix.setText("Numar Fix");

        bRefresh.setText("Refresh Table!");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        jLabel6.setText("Ordonare:");

        bgOrdonare.add(jrbOrdoneazaNume);
        jrbOrdoneazaNume.setText("Nume");
        jrbOrdoneazaNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOrdoneazaNumeActionPerformed(evt);
            }
        });

        bgOrdonare.add(jrbOrdoneazaPrenume);
        jrbOrdoneazaPrenume.setText("Prenume");
        jrbOrdoneazaPrenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOrdoneazaPrenumeActionPerformed(evt);
            }
        });

        bgOrdonare.add(jrbOrdoneazaCnp);
        jrbOrdoneazaCnp.setText("Cnp");
        jrbOrdoneazaCnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOrdoneazaCnpActionPerformed(evt);
            }
        });

        bgOrdonare.add(jrbOrdoneazaNumar);
        jrbOrdoneazaNumar.setText("Numar");
        jrbOrdoneazaNumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOrdoneazaNumarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAdauga, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(bSterge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bModifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNume)
                                    .addComponent(lPrenume)
                                    .addComponent(lCnp)
                                    .addComponent(lNrTel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbNrFix)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbNrMobil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfCnp)
                                            .addComponent(tfPrenume)
                                            .addComponent(tfNume)
                                            .addComponent(tfNrTelefon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbOrdoneazaPrenume)
                                    .addComponent(jrbOrdoneazaNume)
                                    .addComponent(jrbOrdoneazaCnp)
                                    .addComponent(jrbOrdoneazaNumar)))
                            .addComponent(bRefresh))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNume)
                    .addComponent(tfNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrenume)
                    .addComponent(tfPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCnp)
                    .addComponent(tfCnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNrTel)
                    .addComponent(tfNrTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbNrMobil))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNrFix)))
                .addGap(12, 12, 12)
                .addComponent(bAdauga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bSterge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bModifica)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jrbOrdoneazaNume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbOrdoneazaPrenume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbOrdoneazaCnp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbOrdoneazaNumar)
                .addGap(18, 18, 18)
                .addComponent(bRefresh)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.ipady = 182;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        jlPoza.setMaximumSize(new java.awt.Dimension(200, 150));
        jlPoza.setMinimumSize(new java.awt.Dimension(200, 150));
        jlPoza.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jpReclameLayout = new javax.swing.GroupLayout(jpReclame);
        jpReclame.setLayout(jpReclameLayout);
        jpReclameLayout.setHorizontalGroup(
            jpReclameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReclameLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jlPoza, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jpReclameLayout.setVerticalGroup(
            jpReclameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReclameLayout.createSequentialGroup()
                .addComponent(jlPoza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 204, 0);
        getContentPane().add(jpReclame, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 429;
        gridBagConstraints.ipady = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jmFile.setText("File");
        jmFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFileActionPerformed(evt);
            }
        });

        jOpen.setText("Open db");
        jOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenActionPerformed(evt);
            }
        });
        jmFile.add(jOpen);

        jSave.setText("Save db");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });
        jmFile.add(jSave);
        jmFile.add(jSeparator1);

        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        jmFile.add(jExit);

        jMenuBar1.add(jmFile);

        jmAdauga.setText("Abonati");

        jAdauga.setText("Adauga");
        jAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdaugaActionPerformed(evt);
            }
        });
        jmAdauga.add(jAdauga);

        jSterge.setText("Sterge");
        jSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStergeActionPerformed(evt);
            }
        });
        jmAdauga.add(jSterge);

        jModifica.setText("Modifica");
        jmAdauga.add(jModifica);

        jMenu2.setText("Ordonare");

        jMenuItem1.setText("dupa nume");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("dupa prenume");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("dupa cnp");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("dupa numar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jmAdauga.add(jMenu2);

        jMenuBar1.add(jmAdauga);

        jmHelp.setText("Help");
        jmHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHelpActionPerformed(evt);
            }
        });

        jConnect.setText("Inregistrare");
        jConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnectActionPerformed(evt);
            }
        });
        jmHelp.add(jConnect);
        jmHelp.add(jSeparator2);

        jAbout.setText("About");
        jAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAboutActionPerformed(evt);
            }
        });
        jmHelp.add(jAbout);

        jMenuBar1.add(jmHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFileActionPerformed
    
    }//GEN-LAST:event_jmFileActionPerformed

    private void jOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenActionPerformed
        try{
            connectDataBase();
            new JOptionPane().showMessageDialog(this, "DB connected");
        }catch(Exception e){
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jOpenActionPerformed

    private void bAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugaActionPerformed
 
        if(connectDataBase() == true){
            if(rbNrMobil.isSelected()){
                try {
                    rs = s.executeQuery("SELECT * FROM abonat");
                    rs.moveToInsertRow();
                    String nume = tfNume.getText();
                    String prenume = tfPrenume.getText();
                    long cnp = Long.valueOf(tfCnp.getText());
                    String nr = tfNrTelefon.getText();
                    int nrMobil = Integer.parseInt(nr);
                    rs.updateString("NUME", nume);
                    rs.updateString("PRENUME",prenume);
                    rs.updateLong("CNP", cnp);
                    rs.updateInt("NRTEL", nrMobil);
                    rs.insertRow();
                    new JOptionPane().showMessageDialog(this, "Salvat cu succes tel mobil");
                    
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(rbNrFix.isSelected()){
                try {
                    rs = s.executeQuery("SELECT * FROM abonat");
                    rs.moveToInsertRow();
                    String nume = tfNume.getText();
                    String prenume = tfPrenume.getText();
                    long cnp = Long.valueOf(tfCnp.getText());
                    String nr = tfNrTelefon.getText();
                    int nrFix = Integer.parseInt(nr);
                    rs.updateString("NUME", nume);
                    rs.updateString("PRENUME",prenume);
                    rs.updateLong("CNP", cnp);
                    rs.updateInt("NRTEL", nrFix);
                    rs.insertRow();
                
                    new JOptionPane().showMessageDialog(this, "Salvat cu succes tel mobil");
                    
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            new JOptionPane().showMessageDialog(this, "Incarca baza de date!");
        }
    }//GEN-LAST:event_bAdaugaActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
        if(connectDataBase() == true){
            try{
                
                rs = s.executeQuery("SELECT * FROM abonat");
                l = new ArrayList<Abonat>(); 
                while(rs.next()){
                    if(rs.getString("NRTEL").startsWith("7")){
                        l.add(new Abonat(rs.getString("NUME"),rs.getString("PRENUME"),rs.getLong("CNP"),new NrMobil(rs.getLong("NRTEL"))));
                        model = new CarteDeTelefon(l);
                        jTable1.setModel(model);
                    }else if (rs.getString("NRTEL").startsWith("2")){
                    
                        l.add(new Abonat(rs.getString("NUME"),rs.getString("PRENUME"),rs.getLong("CNP"),new NrFix(rs.getLong("NRTEL"))));
                        model = new CarteDeTelefon(l);
                        jTable1.setModel(model);
                    }
                }
           
            }catch(SQLException e){
                System.err.println(e.getMessage());
            }
        }else{
            new JOptionPane().showMessageDialog(this, "Conectati baza de date");
        }
    }//GEN-LAST:event_bRefreshActionPerformed

    private void jConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnectActionPerformed
        // TODO add your handling code here:
        
        
        gPass = new GUIPass();
        gPass.setVisible(true);
       
    }//GEN-LAST:event_jConnectActionPerformed

    private void jmHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHelpActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jmHelpActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        if(connectDataBase() == true){
            try {
                rs.refreshRow();
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            new JOptionPane().showMessageDialog(this, "Conectati baza de date!");
        }
    }//GEN-LAST:event_jSaveActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void jAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdaugaActionPerformed
        if(connectDataBase() == true){
            if(rbNrMobil.isSelected()){
                try {
                    rs = s.executeQuery("SELECT * FROM abonat");
                    rs.moveToInsertRow();
                    String nume = tfNume.getText();
                    String prenume = tfPrenume.getText();
                    long cnp = Long.valueOf(tfCnp.getText());
                    String nr = tfNrTelefon.getText();
                    int nrMobil = Integer.parseInt(nr);
                    rs.updateString("NUME", nume);
                    rs.updateString("PRENUME",prenume);
                    rs.updateLong("CNP", cnp);
                    rs.updateInt("NRTEL", nrMobil);
                    rs.insertRow();
                    new JOptionPane().showMessageDialog(this, "Salvat cu succes tel mobil");
                    
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(rbNrFix.isSelected()){
                try {
                    rs = s.executeQuery("SELECT * FROM abonat");
                    rs.moveToInsertRow();
                    String nume = tfNume.getText();
                    String prenume = tfPrenume.getText();
                    long cnp = Long.valueOf(tfCnp.getText());
                    String nr = tfNrTelefon.getText();
                    int nrFix = Integer.parseInt(nr);
                    rs.updateString("NUME", nume);
                    rs.updateString("PRENUME",prenume);
                    rs.updateLong("CNP", cnp);
                    rs.updateInt("NRTEL", nrFix);
                    rs.insertRow();
                
                    new JOptionPane().showMessageDialog(this, "Salvat cu succes tel mobil");
                    
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            new JOptionPane().showMessageDialog(this, "Incarca baza de date!");
        }
    }//GEN-LAST:event_jAdaugaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        model.ordoneaza(Criterii.Dupa_Cnp);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jrbOrdoneazaPrenumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOrdoneazaPrenumeActionPerformed
        // TODO add your handling code here:
        model.ordoneaza(Criterii.Dupa_Prenume);
    }//GEN-LAST:event_jrbOrdoneazaPrenumeActionPerformed

    private void jrbOrdoneazaNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOrdoneazaNumeActionPerformed
        // TODO add your handling code here:
        model.ordoneaza(Criterii.Dupa_Nume);
    }//GEN-LAST:event_jrbOrdoneazaNumeActionPerformed

    private void jrbOrdoneazaCnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOrdoneazaCnpActionPerformed
        // TODO add your handling code here:
        model.ordoneaza(Criterii.Dupa_Cnp);
    }//GEN-LAST:event_jrbOrdoneazaCnpActionPerformed

    private void jrbOrdoneazaNumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOrdoneazaNumarActionPerformed
        // TODO add your handling code here:
        model.ordoneaza(Criterii.Dupa_NrTel);
    }//GEN-LAST:event_jrbOrdoneazaNumarActionPerformed

    private void bStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStergeActionPerformed
        // TODO add your handling code here:
        if(connectDataBase() == true){
            try {
                rs = s.executeQuery("SELECT * FROM abonat");
                rs.absolute(jTable1.getSelectedRow() + 1);
                rs.deleteRow();
                new JOptionPane().showMessageDialog(this, "S-a sters cu succes!");
                refreshDB();
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            new JOptionPane().showMessageDialog(this, "Incarcati baza de date");
        }
    }//GEN-LAST:event_bStergeActionPerformed

    private void bModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificaActionPerformed
        // TODO add your handling code here:
        if(jTable1.isCellEditable(jTable1.getSelectedRow(), jTable1.getSelectedColumn())){
            try {
                rs = s.executeQuery("SELECT * FROM abonat");
                rs.absolute(jTable1.getSelectedRow() +1 );
                rs.updateRow();
                new JOptionPane().showMessageDialog(this, "S-a editat cu succes!");
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            new JOptionPane().showMessageDialog(this, "ERROR");
        }
        
    }//GEN-LAST:event_bModificaActionPerformed

    private void jAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAboutActionPerformed
        // TODO add your handling code here:
        new JOptionPane().showMessageDialog(this, " \"Carte de telefon \" \n "
                + "Aceasta aplicatie a fost realizata de Voicu Eduard-Robert. \n"
                + "Aplicatia salveaza intr-o baza de date abonatii unei carti \n"
                + "de telefon,se pot adauga,sterge,modifica abonatii dupa nevoile\n "
                + "fiecaruia.");
    }//GEN-LAST:event_jAboutActionPerformed

    private void jStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStergeActionPerformed
        // TODO add your handling code here:
        if(connectDataBase() == true){
            try {
                rs = s.executeQuery("SELECT * FROM abonat");
                rs.absolute(jTable1.getSelectedRow() + 1);
                rs.deleteRow();
                new JOptionPane().showMessageDialog(this, "S-a sters cu succes!");
                refreshDB();
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            new JOptionPane().showMessageDialog(this, "Incarcati baza de date");
        }
    }//GEN-LAST:event_jStergeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        model.ordoneaza(Criterii.Dupa_Nume);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        model.ordoneaza(Criterii.Dupa_Prenume);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        // TODO add your handling code here:
        model.ordoneaza(Criterii.Dupa_NrTel);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    // metoda care deschide baza de date
    public boolean connectDataBase(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/cartedetelefon","root","robert406661");
            s = c.createStatement( ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE );
            
        } catch (Exception ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }
    
    //metoda care inchide baza de date
    public boolean closeDB(){
        try {
            connectDataBase();
            c.close();
            s.close();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }
    
    //metoda care afiseaza banner-ul cu reclame
    
    public void banner(){
         i1 = new ImageIcon(getClass().getResource("picture1.jpg"));
         i2 = new ImageIcon(getClass().getResource("picture1.jpg"));
         i3 = new ImageIcon(getClass().getResource("picture1.jpg"));

        ActionListener task = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                do{
                    randCurent = rand.nextInt(3);
                }while(randCurent == d);
                d = randCurent;
                if(randCurent == 3){
                    i3 = new ImageIcon(getClass().getResource("picture1.jpg"));
                    jlPoza.setIcon(i3);
                    repaint();
                }else if(randCurent == 2){
                    i2 = new ImageIcon(getClass().getResource("picture2.jpg"));
                    jlPoza.setIcon(i2);
                    repaint();
                }else if(randCurent == 1){
                    i1 = new ImageIcon(getClass().getResource("picture1.jpg"));
                    jlPoza.setIcon(i1);
                    repaint();
                }
            }
        };
        javax.swing.Timer t = new javax.swing.Timer(600, task);
        t.addActionListener(task);
        t.setDelay(2000);
        t.start();
        
    }
    
    //metoda care afiseaza in JTable, valorile din baza de date
    
    public void refreshDB(){
        if(connectDataBase() == true){
            try{
                
                rs = s.executeQuery("SELECT * FROM abonat");
                l = new ArrayList<Abonat>(); 
                while(rs.next()){
                    if(rs.getString("NRTEL").startsWith("7")){
                        l.add(new Abonat(rs.getString("NUME"),rs.getString("PRENUME"),rs.getLong("CNP"),new NrMobil(rs.getLong("NRTEL"))));
                        model = new CarteDeTelefon(l);
                        jTable1.setModel(model);
                    }else if (rs.getString("NRTEL").startsWith("2")){
                    
                        l.add(new Abonat(rs.getString("NUME"),rs.getString("PRENUME"),rs.getLong("CNP"),new NrFix(rs.getLong("NRTEL"))));
                        model = new CarteDeTelefon(l);
                        jTable1.setModel(model);
                    }
                }
           
            }catch(SQLException e){
                System.err.println(e.getMessage());
            }
        }else{
            new JOptionPane().showMessageDialog(this, "Conectati baza de date");
        }
    }
    
    public void setMnemonics(){
        bAdauga.setMnemonic(KeyEvent.VK_A);
        bSterge.setMnemonic(KeyEvent.VK_S);
        bModifica.setMnemonic(KeyEvent.VK_M);
        jrbOrdoneazaNume.setMnemonic(KeyEvent.VK_N);
        jrbOrdoneazaPrenume.setMnemonic(KeyEvent.VK_P);
        jrbOrdoneazaCnp.setMnemonic(KeyEvent.VK_C);
        jrbOrdoneazaNumar.setMnemonic(KeyEvent.VK_U);
        lNume.setDisplayedMnemonic(KeyEvent.VK_U);
        lPrenume.setDisplayedMnemonic(KeyEvent.VK_R);
        lCnp.setDisplayedMnemonic(KeyEvent.VK_N);
        lNrTel.setDisplayedMnemonic(KeyEvent.VK_L);
        rbNrMobil.setMnemonic(KeyEvent.VK_O);
        rbNrFix.setMnemonic(KeyEvent.VK_F);
        jmFile.setMnemonic(KeyEvent.VK_I);
        jmAdauga.setMnemonic(KeyEvent.VK_D);
        jmHelp.setMnemonic(KeyEvent.VK_H);
        jOpen.setMnemonic(KeyEvent.VK_O);
        jSave.setMnemonic(KeyEvent.VK_V);
        jExit.setMnemonic(KeyEvent.VK_X);
        jAdauga.setMnemonic(KeyEvent.VK_G);
        jAbout.setMnemonic(KeyEvent.VK_B);
        jConnect.setMnemonic(KeyEvent.VK_I);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdauga;
    private javax.swing.JButton bModifica;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSterge;
    private javax.swing.ButtonGroup bgCautare;
    private javax.swing.ButtonGroup bgNumarTelefon;
    private javax.swing.ButtonGroup bgOrdonare;
    private javax.swing.JMenuItem jAbout;
    private javax.swing.JMenuItem jAdauga;
    private javax.swing.JMenuItem jConnect;
    private javax.swing.JMenuItem jExit;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jModifica;
    public javax.swing.JMenuItem jOpen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JMenuItem jSave;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem jSterge;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlPoza;
    private javax.swing.JMenu jmAdauga;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JPanel jpReclame;
    private javax.swing.JRadioButton jrbOrdoneazaCnp;
    private javax.swing.JRadioButton jrbOrdoneazaNumar;
    private javax.swing.JRadioButton jrbOrdoneazaNume;
    private javax.swing.JRadioButton jrbOrdoneazaPrenume;
    private javax.swing.JLabel lCnp;
    private javax.swing.JLabel lNrTel;
    private javax.swing.JLabel lNume;
    private javax.swing.JLabel lPrenume;
    private javax.swing.JRadioButton rbNrFix;
    private javax.swing.JRadioButton rbNrMobil;
    private javax.swing.JTextField tfCnp;
    private javax.swing.JTextField tfNrTelefon;
    private javax.swing.JTextField tfNume;
    private javax.swing.JTextField tfPrenume;
    // End of variables declaration//GEN-END:variables
}
